// ============================================================
// File:        KoiRacerType.js
// Path:        client/src/modules/racer-types/KoiRacerType.js
// Project:     RaceArena
// Description: Koi fish racer — SpriteRacerType with per-coat pattern masks.
//              Sprite: 16-frame swim cycle, 4096×256 sheet (256×256 per frame, tight-cropped).
//              tintMode: 'mask' with per-coat patternMask URLs so each of the
//              16 coats uses a different koi pattern (Kohaku / Sanke / Showa /
//              Ogon). Masks are generated by scripts/gen-koi-patterns.mjs.
//              Speed: 0.95 — graceful fish glide, slightly below horse pace.
// ============================================================

import { SpriteRacerType } from './SpriteRacerType.js';
import { makeGenericDustTrail } from './genericDustTrail.js';
import { KOI_COATS } from './koiCoats.js';

const SPRITE_URL = '/assets/racers/koi-swim.png';

export const PATTERNS = [
  '/assets/racers/koi-mask-kohaku.png',
  '/assets/racers/koi-mask-sanke.png',
  '/assets/racers/koi-mask-showa.png',
  '/assets/racers/koi-mask-ogon.png',
];

export const KoiRacerType = new SpriteRacerType({
  id: 'koi',
  emoji: '🐟',

  spriteUrl: SPRITE_URL,
  frameWidth: 256,
  frameHeight: 256,
  frameCount: 16,
  basePeriodMs: 1600,
  baseRotationOffset: Math.PI / 2,
  displaySize: 52,
  bodyFillX: 0.578,
  bodyFillY: 0.914,
  tintMode: 'mask',

  coats: KOI_COATS,
  defaultCoatId: 'kohaku-crimson',

  primaryColor: '#e8682a',
  accentColor: '#f0ede8',

  leaderRingColor: '#f0a040',
  leaderEllipseRx: 20,
  leaderEllipseRy: 12,

  speedMultiplier: 0.95,

  trailFactory: makeGenericDustTrail({
    color: '#88c8e8',
    ttl: 22,
    spawnProbability: 0.4,
    minRadius: 1,
    maxRadius: 3,
    alphaCoeff: 0.2,
  }),
  surfaceClasses: ['water'],
});
